### ISSUE TITLE
주제 확정

### ISSUE THREAD

**Issue by Bakhyoungwoo** [Bakhyoungwoo/Opensource-destiny-#1]
현 주제인 영화 및 드라마 예측을 유지할까?
다른주제를 할까?

**Comment by MuHaRVEY** [comment]
회차별, 연도별 평균 점수 데이터를 기반으로 향후 토익의 난이도를 예측하는 주제는 어떠할까?

**Comment by wan-su-2020** [comment]
현 주제는 차별성이 떨어져서 다른 주제를 정하는 건 어떨까? 
우리가 생각했던 주제 중 사용자의 신체조건을 바탕으로 옷을 예측해서 추천해주는 프로그램이 지금 주제보다 차별성을 두기 조금 더 좋을 거 같아.

**Comment by MuHaRVEY** [comment]
그러면 사용자에게 조건을 바탕으로 옷을 추천해주는 프로그램에,

사용자가 가려고 하는 특정 행사 같은 상황에 어울리는 옷을 추천해주는 방식을 추가해서 차별성을 더하면 어떨까

**Comment by Bakhyoungwoo** [comment]
정리하자면 사용자의 신체 조건을 바탕으로 코디(옷)을 예측하는 프로그램이 주제고
이 주제에 대한 차별점은 특정 상황에 어울리는 코디를 추천하는 방식으로 정하도록 할게요
