### ISSUE TITLE
파이썬 크롤링한 엑셀 데이터 읽어와 사용자에게 코디를 추천하는 함수 오류 발생

### ISSUE THREAD

**Issue by MuHaRVEY** [Bakhyoungwoo/Opensource-destiny-#13]
현재 구현한 함수에서 엑셀에 상황에 대한 분류가 여러가지인 경우, 
랜덤으로 코디를 추천할때, 다른 상황에 대한 코디를 추천하는 오류가 발생하였습니다.

조건문과 관련하여 반복문을 수정하는 작업을 시작하겠습니다.

**Comment by wan-su-2020** [comment]
현재 발생한 오류가 옷 title 전체에서 랜덤으로 옷을 뽑았던 것이 문제인 거 같습니다. 현재 ex) 결혼식관련 코디를 쳤을때 결혼식 관련된 옷이 랜덤으로 추천되는게 아닌 옷 title 전체에서 랜덤으로 뽑습니다. 이것과 관련된 조건문을 수정하여 코디와 관련된 상황에 맞게 옷을 추천하는 방향으로 수정해야될 거 같습니다.

**Comment by Bakhyoungwoo** [comment]
아예 자료 자체를 카테고리 별로 미리 분류하는 것도 하나의 방법이 될 수 있을 것 같습니다. 분류한 후 함수를 통해 호출하는 방법도 괜찮을 수도 있을 것 같습니다.
