### ISSUE TITLE
브랜치 안의 파일명 재정리 

### ISSUE THREAD

**Issue by wan-su-2020** [Bakhyoungwoo/Opensource-destiny-#14]
현재 가지고 있는 Feature_crawling 브랜치 안에 있는 crawling 코드를 모든 웹 페이지에 사용할 수 있는 것이 아닌 그 페이지에 한정하여 사용할 수 있습니다. 이에 따라 crawling을 웹 페이지마다 다르게 구현하여야 하는데 이에 따라서 브랜치 안의 파일명을 좀 더 세부적으로 나눠야 될 것 같습니다.

**Comment by MuHaRVEY** [comment]
내부에 파일을 commit 할때 좀더 세부적으로 이름을 작성할 필요성이 있어보입니다.
가령 crawling_lookpin_wedding.py
기능_사이트_상황 
이런식으로 올려서 기능과 사이트, 상황 등에 대한 명명을 정확히 하면 좋을 거 같습니다.

**Comment by Bakhyoungwoo** [comment]
의류의 경우는 clothes_crawling_사이트 이름_의류 명(ex : 맨투맨).py 등으로 작성하는게 좋을 듯 합니다.
