### ISSUE TITLE
생각해본 구현할 수 있는 차별점

### ISSUE THREAD

**Issue by MuHaRVEY** [Bakhyoungwoo/Opensource-destiny-#17]
현재 저희는 사용자의 옷을 입을 상황에 따라 코디를 추천해주는 방식으로의 구현을 거의 완료하였습니다.
하지만, 이는 대부분의 유명 홈페이지에서도 이미 제공하는 기능이라고 볼 수 있습니다.

때문에 **_색깔에 따라 옷을 추천해주는 기능_**을 포함하면 어떨까? 라는 의견입니다.
흔히들 말하는 **'옷 색조합 표'**라는 것을 통해 상하의 옷의 어울리는 색깔에 따른 추천을 해주는 것입니다.

현재의 엑셀 데이터에 새로운 열로서 color 열을 추가하고, 어울리는 색깔끼리의 case를 나누어두면 어울리는 색깔에 따른 추천도 가능할 것으로 보입니다.

**Comment by Bakhyoungwoo** [comment]
추가로 의류 사이트라고 했을때 딱 떠오르는 사이트 들의 경우 가격들을 비교해 주는 기능은 없었던 것 같아서 이것도 추가해보면 좋을 듯 합니다.

**Comment by wan-su-2020** [comment]
색 조합표와 함께 서로 어울리는 색깔의 상하의를 사용자에게 보여주는 것도 좋을 것 같습니다.
