### ISSUE TITLE
8주차 중간고사 발표 준비

### ISSUE THREAD

**Issue by Bakhyoungwoo** [Bakhyoungwoo/Opensource-destiny-#18]
![image](https://user-images.githubusercontent.com/128560371/232936081-c0720593-0ad7-44ad-b73f-75a58305e4d1.png)

4월 25일까지 발표자료를 제출해야 하는데 다음주는 시험이 많으니 이번주 금요일이나 주말에 만나서 발표를 준비할까 하는데 어떤가요?

**Comment by wan-su-2020** [comment]
금요일이나 토요일이 좋은거 같습니다

**Comment by MuHaRVEY** [comment]
금요일 수학II 교양 시험 끝나고, 점심시간 이후로 시간 괜찮습니다
