### ISSUE TITLE
색깔 - 상황 함수 통합 시작했습니다. + 향후 구현 예정 내용

### ISSUE THREAD

**Issue by MuHaRVEY** [Bakhyoungwoo/Opensource-destiny-#20]
### **현재 상황**:
상황을 입력 받은 후, 색깔을 입력받음.

-> 엑셀의 coid(데이트룩,결혼식룩 등의 상황을 가리키는 열)열과 color(검은색,회색,파란색 등의 색깔을 가리키는 열)에서 사용자가 입력한 두 정보와 가장 유사한 단어를 각각 추출

따라서 데이트룩, 검은색 이렇게 입력했을 경우 데이트룩의 상황과 검은색의 색깔이 동시에 있는 행에 있는 title열(옷, 코디 이름)을 사용자에게 추천해줌.

### **현재 코드의 문제점.**
1.  사용자가 마음에 들지 않는다고 했을 경우, 이전에 추천했던걸 다시 추천해주는 것에 대한 문제점 -> 아직 예외 상황을 코드로 구현하지 못했음. 구현 예정
2.  위의 문제점과 더불어 엑셀에 더 이상 추천할 옷이 없을 경우, 사용자가 원하는 옷이 우리의 데이터에 없음을 알리고 반복을 종료해주는 기능을 아직 구현하지 못했음 .구현 예정

**Comment by Bakhyoungwoo** [comment]
현재 엑셀로 들어간 파일을 불러오는 게 진행되었다는 것인가요?

**Comment by MuHaRVEY** [comment]
과거 박형우 학생과 김완수 학생이 크롤링한 엑셀을 바탕으로 데이터를 유사도 기반으로 추출하여 사용자에게 원하는 내용을 추천해주는 것까지는 진행되었다는 말이었습니다. 문제점 내용은 향후 수정 보완이어나가겠습니다
