### ISSUE TITLE
변수명 통일에 대한 필요성

### ISSUE THREAD

**Issue by Bakhyoungwoo** [Bakhyoungwoo/Opensource-destiny-#21]
현재 각각 구현하고 있는 부분에서 공통적으로 들어가는 변수들이 있는데 그 이름을 통일해야 할 것 같습니다. 예를 들어 상황을 입력받는 경우 상황을 저장하는 변수가 서로 다를경우 저희가 나중에 하나로 합쳐 구동할때 변수 명이 같지 않아서 수정해야합니다.

**Comment by MuHaRVEY** [comment]
현재 사이트에서 옷이나 코디의 이름을 title로서 추출해놓았는데
상황에 대한 이름이 codi인 것이 조금 혼동을 불러올 수도 있을듯합니다.

사이트에서 코디나 옷 이름을 불러오는 것을 codi로 변경하여 통일하고 
데이트룩, 결혼식룩, 캠퍼스룩 등 상황을 situtation으로 통일하고
색깔을 color로 통일하는게 어떨까 합니다.

**Comment by wan-su-2020** [comment]
확실히 좀 더 세부적으로 통일할 필요가 있겠습니다.  그리고 주석을 다는 것도 넘겨 받는 입장에서 이해하기에 좀 더 편하지 않을까 생각합니다.

**Comment by Bakhyoungwoo** [comment]
그 외에 다른 부분에서 변수 명이 동일하게 사용될 경우 변수 명_상황 이런 식으로 작성 하는게 좋을 것 같습니다
예를 들어 codi_situation이런 식이면 좋을 것 같네요.
