### ISSUE TITLE
진행상황 확인 및 계획 구상

### ISSUE THREAD

**Issue by Bakhyoungwoo** [Bakhyoungwoo/Opensource-destiny-#23]
현재까지 저희가 만든 프로젝트의 전체적인 진행도를 정리해야 할 것 같습니다. 매주 주기적으로 회의를 진행하면서 각자의 부분을 만들어 주고 계시지만 각자 만들다 보니 서로의 진도가 어디까지 나갔는지 확인 이 어려운 부분이 있어서 정리할 필요가 있어 보입니다. 그리고 그에 따라 앞으로의 계획을 구상해 보면 될 것 같습니다.

**Comment by MuHaRVEY** [comment]
동의합니다. 현재 저의코드와 박형우 학생의 코드를 최종적으로 합쳐야 하는 작업이 필요할텐데, 
김완수 학생의 크롤링 데이터를 기반으로 해야하는 것에 반면에 현재 코드에서 쓰이는 엑셀 열의 개수가 다른 것을 파악했습니다.
내일 회의를 통해 코드를 어떤식으로 작동하게 할지, 엑셀의 열을 몇개, 무슨 열을 사용할지에 대해 논의해봅시다.
