### ISSUE TITLE
GUI 디자인

### ISSUE THREAD

**Issue by Bakhyoungwoo** [Bakhyoungwoo/Opensource-destiny-#24]
저희가 만들 프로그램의 디자인을 정할 필요가 있습니다. 원하시는 디자인이 있으시면 여기에 올려주신다면 최대한 그에 맞게 꾸며보겠습니다.

**Comment by MuHaRVEY** [comment]
시작 화면에서 사용자가 의류 추천 프로그램임을 직관적으로 알 수 있도록 옷걸이, 옷장, 피팅룸과 같이 꾸며 놓을 필요가 있을 듯 합니다.

**Comment by Bakhyoungwoo** [comment]
좋은 생각인 것 같습니다. 현재 바탕이 회색인데 혹시 원하시는 색이 있으실까요?

**Comment by wan-su-2020** [comment]
색깔은 어두운계열(너무 어두운 것은 제외)이 좋을 것 같습니다. 현재 뽑아온 옷이나 코디의 배경을 보면 대부분 흰색이거나 밝은 배경이어서 어두운 계열이 옷이 돋보이기에 좋을 것 같습니다.

**Comment by Bakhyoungwoo** [comment]
알겠습니다. 수정해 보겠습니다.
