### ISSUE TITLE
현재 데이터 수집한 파일로 여러개의 코디 파일과 상,하의 파일들이 존재합니다. 이러한  파일들을 하나의 파일로 합칠지 아니면 따로 구분을 하여 파일을 두어야하는지 논의가 필요합니다.

### ISSUE THREAD

**Issue by wan-su-2020** [Bakhyoungwoo/Opensource-destiny-#26]

**Comment by MuHaRVEY** [comment]
기능에 대한 논의를 충분히 마친 뒤에 엑셀의 통합을 어떻게 이루어야 할지 생각해보아야 할 것 같습니다.

작성한 코드를 tkinter 형식으로 변환하는 과정에서 사용자에게 값을 입력받아 버튼으로 눌러 동작하고 있는데,

버튼에 대한 기능을 수행할 수 있도록 엑셀을 준비해야하기 때문입니다.

**Comment by Bakhyoungwoo** [comment]
상의와 하의 그리고 코디 이렇게 3개의 파일로 두어야 할 것 같습니다.

**Comment by wan-su-2020** [comment]
좋습니다. 이러한 방향으로 데이터 수집 및 파일 통합을 하도록 하겠습니다.
