### ISSUE TITLE
GUI 관련 논의해야할 부분

### ISSUE THREAD

**Issue by Bakhyoungwoo** [Bakhyoungwoo/Opensource-destiny-#29]
기존의 방식은 하나의 윈도우창에서 계속 다음 파트로 넘어가는 식의 코드로 작성했는데 이것보다 새로운 윈도우창을 띄우는 방식으로 하는게 더 좋을 듯한데 의견 부탁드립니다.

**Comment by MuHaRVEY** [comment]
결과값이 도출될 때만 새로운 창으로 띄워서 보여주는 것은 어떨까요?

**Comment by Bakhyoungwoo** [comment]
그것 도 좋은 생각입니다. 혹시 색 같은 부분은 없을까요?

**Comment by Bakhyoungwoo** [comment]
현재 기술상의 문제로 값이 입력되면 일단 새로운 윈도우 창을 띄우는 방향으로 해결 중입니다.

**Comment by Bakhyoungwoo** [comment]
의견이 따로 없으신 것 같아서 값을 입력하면 새로운 창을 만들어서 그 창안에 표현하는 방식으로 진행하겠습니다.
