### ISSUE TITLE
사용자 인터페이스 방식 정하기

### ISSUE THREAD

**Issue by MuHaRVEY** [Bakhyoungwoo/Opensource-destiny-#3]
코드 구현 후, 우리가 만든 서비스를 사용자에게 어떠한 인터페이스로 제공하는 게 좋을지 의견을 나누어 봅시다.

**Comment by Bakhyoungwoo** [comment]
우선 사용자의 정보를 입력하는 곳이 있어야 할 것 같습니다.

**Comment by wan-su-2020** [comment]
사용자에게 사용할 수 있는 메뉴를 제공할 수 있어야 할 것 같습니다.

**Comment by Bakhyoungwoo** [comment]
인터페이스 구현은 파이썬의 gui를 이용하는 게 어떨까 싶습니다.
예를 들어 tkinter가 있습니다.

**Comment by Bakhyoungwoo** [comment]
우리가 구현하기에 그나마 괜찮은 방식이라고 생각합니다.

**Comment by MuHaRVEY** [comment]
GUI 방식 좋을 거 같네요
