### ISSUE TITLE
상황에 대한 추천코디 검색어

### ISSUE THREAD

**Issue by Bakhyoungwoo** [Bakhyoungwoo/Opensource-destiny-#32]
검색어를 어떻게 입력해야하는지 이야기 할 필요가 있어보입니다.

**Comment by MuHaRVEY** [comment]
제가 만들었던 코드는 총 4개의 열을 필요로합니다.

title, codi, color, gender

입력된 값들은 코드에서 정의했던 
```python
def get_similar_words(word, words_list):
```
이 부분을 통해 입력한 단어의 유사도를 측정하여 필터링합니다.
가령 성별을 '남성', 상황을 '미니멀', 색깔을 '회색'으로 입력하면 아래의 내용에서는 남자친구의 미니멀 결혼식 하객룩이 추천되게 될 것입니다.

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/rkddn/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/rkddn/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



  | title | codi | color | gender
-- | -- | -- | -- | --
0 | ⭐캐주얼 셋업 수트 코디⭐ | 데이트룩, 캐주얼, 미니멀, 모던&포멀, 댄디 | 검은색 | 남성
1 | 베이지 무드의 셋업코디 | 데일리룩, 데이트룩, 비즈니스룩, 미니멀, 모던&포멀 | 네이비색 | 여성
2 | 남자친구의 미니멀 결혼식 하객룩 | 데이트룩, 미니멀, 모던&포멀, 댄디, 유니크 | 회색 | 남성
3 | 💙봄가을 입기좋은 셋업코디💙 | 댄디, 데일리룩, 데이트룩, 미니멀, 모던&포멀, 댄디 | 회색 | 여성



</body>

</html>

**Comment by Bakhyoungwoo** [comment]
상황이 결혼식이 되어야 하는게 아닌가요?

**Comment by MuHaRVEY** [comment]
엑셀 파일이 현재 저희의 무신사 크롤링이 아닌
과거 시도했던 룩핀 파일이라 그렇습니다.

예시일 뿐이며 사이트에서 제공했던 정보를 옷 이름에 대한 열과 상황에 대한 열에 나눠서 생기는 일종의 문제일 것입니다.

만일 상황에 대한 정보를 옷 이름에 함께 있는 결혼, 가을 등의 키워드 예를들어 결혼식 @₩%% 정장, 가을 데이트 룩 등의 이름으로 사이트에 있다면  저희도 코드를 조금 수정하여 title 내에서 키워드를 필터링 하는 것도 하나의 방법일 것입니다.

**Comment by Bakhyoungwoo** [comment]
그렇게 검색할때의 결과값 하나만 예를 들어주실래요? 지금 수정중입니다.

**Comment by MuHaRVEY** [comment]
가령 남성, 데이트, 검은색을 입력하였을 경우 ⭐캐주얼 셋업 수트 코디⭐이 출력되어야 합니다.
