### ISSUE TITLE
비슷한 가격대의 옷 추천 코드에, 같은 색 옷 추천 기능 추가도중 오류 발생 (해결하였습니다.)

### ISSUE THREAD

**Issue by MuHaRVEY** [Bakhyoungwoo/Opensource-destiny-#33]
```python
    # 입력한 옷과 같은 색의 옷 추천
    cloth_color = matching_rows.iloc[0]['color']  # 입력한 옷과 같은 색깔 정보
    same_color_clothes = df.loc[df['color'] == cloth_color]  # 색깔이 같은 옷 추출

    #같은 색깔의 옷 추천 리스트 생성
    recommend_clothes_same_color = []
    for _, row in same_color_clothes.iterrows():
        if row['title'] != cloth_name:
            recommend_clothes_same_color.append(row['title'])

    # 추천할 옷이 있다면 출력
    if len(recommend_clothes_same_color) > 0:
        print(f"입력한 옷과 같은 색의 옷 추천: {recommend_clothes_same_color}")
    else:
        print("추천할 같은 색의 옷이 없습니다.")
```

iloc() 함수를 사용해보려 했는데 생각한 기능이 아닌듯합니다.
다시 수정해보겠습니다.

**Comment by MuHaRVEY** [comment]
다음과 같이 수정하여 해결하였습니다.
``` python
# 입력한 옷과 같은 색의 옷 추천
cloth_color_list = matching_rows['color'].tolist()  # 입력한 옷과 같은 색깔 정보 리스트로 변환
same_color_clothes = df.loc[df['color'].isin(cloth_color_list)]  # 색깔이 같은 옷 추출

recommend_clothes_same_color = []
for _, row in same_color_clothes.iterrows():
    if row['title'] != cloth_name:
        recommend_clothes_same_color.append(row['title'])

# 추천할 옷이 있다면 출력
if len(recommend_clothes_same_color) > 0:
    print(f"입력한 옷과 같은 색의 옷 추천: {recommend_clothes_same_color}")
else:
    print("추천할 같은 색의 옷이 없습니다.")
```



matching_rows['color'].tolist()를 사용하여 matching_rows 데이터프레임의 'color' 열을 리스트로 변환.
이 리스트에는 입력한 옷과 같은 색깔 정보가 포함됨.

df['color'].isin(cloth_color_list)를 사용하여 데이터프레임의 'color' 열이 입력한 옷과 같은 색깔 리스트에 속하는 경우를 선택.
이를 통해 색깔이 같은 옷만 추출함.

추출된 색깔이 같은 옷을 순회하면서, 각 옷의 'title' 값을 확인함.
 
만약 옷의 'title' 값이 입력한 옷의 이름과 같지 않은 경우에만 recommend_clothes_same_color 리스트에 해당 옷의 'title' 값을 추가하여 입력한 옷 자체는 추천에서 제외토록 함.

recommend_clothes_same_color 리스트에는 입력한 옷과 같은 색깔을 가진 다른 옷의 이름이 포함됨.

**Comment by MuHaRVEY** [comment]
아래와 같이 코드를 작성하여 코드를 짧게 바꾸어봤습니다.

작동 원리는 동일합니다.
```python
    # 입력한 옷과 같은 색의 옷 추천
    cloth_color_list = matching_rows['color'].tolist()  # 입력한 옷과 같은 색깔 정보 리스트로 변환
    same_color_clothes = df.loc[(df['title'] != cloth_name) & (df['color'].isin(cloth_color_list))]  # 색깔이 같은 옷 추출

    recommend_clothes_same_color = same_color_clothes['title'].tolist()

    # 추천할 옷이 있다면 출력
    if len(recommend_clothes_same_color) > 0:
        print(f"입력한 옷과 같은 색의 옷 추천: {recommend_clothes_same_color}")
    else:
        print("추천할 같은 색의 옷이 없습니다.")
```

동작 방식은 이전 방식과 동일합니다.

1. matching_rows['color'].tolist()를 사용하여 matching_rows 데이터프레임의 'color' 열을 리스트로 변환하고 해당 리스트에는 입력한 옷과 같은 색깔 정보가 포함됩니다.

2. df['title'] != cloth_name를 사용하여 데이터프레임의 'title' 열이 입력한 옷의 이름과 같지 않은 경우를 선택함으로써 입력한 옷 자체는 같은 색의 옷을 추천하는 목록에서 제외됩니다.

3. (df['color'].isin(cloth_color_list))를 사용하여 데이터프레임의 'color' 열이 입력한 옷과 같은 색깔 리스트에 속하는 경우를 선택합니다. 이를 통해 색깔이 같은 옷만 추출합니다.

4. 추출된 색깔이 같은 옷의 'title' 열을 리스트로 변환합니다. 이는 same_color_clothes['title'].tolist()를 통해 수행됩니다.

이를 통해 recommend_clothes_same_color 리스트에는 입력한 옷과 같은 색깔을 가진 다른 옷의 이름이 포함됩니다.

**Comment by Bakhyoungwoo** [comment]
성별에 따른 옷의 구분은 없는 건가요

**Comment by MuHaRVEY** [comment]
성별에 대한 기능은 저희가 기존에 tkinter에서 기능을 분리하기로 했기 때문에 CombinedCode에 포함시켰습니다
