### ISSUE TITLE
비슷한 가격, 유사한 색깔 추천 코드에서 영어 이름의 옷 문제점 보완

### ISSUE THREAD

**Issue by MuHaRVEY** [Bakhyoungwoo/Opensource-destiny-#35]
영어 이름의 옷의 경우 사용자가 대소문자를 정확하게 입력하는 것은 무리라고 생각됩니다.
이에 대한 보완을 이어나가도록 하겠습니다.

**Comment by MuHaRVEY** [comment]
해결 후, 오타 및 들여쓰기 수정하였습니다.

**Comment by Bakhyoungwoo** [comment]
해결 하셨다는게 대소문자 상관없이 검색했을 때 무리 없다는 것인가요?

**Comment by MuHaRVEY** [comment]
후에, 조원들과 대소문자 관계없이 작동하는 것을 확인하였습니다.
