### ISSUE TITLE
색조합표 관련 진행방향에 대한 토의

### ISSUE THREAD

**Issue by MuHaRVEY** [Bakhyoungwoo/Opensource-destiny-#36]
현재 대부분의 코드는 사진을 제외한 기능에 대하여 왠만한 기능이 구현되어 있습니다.

마지막 기능으로 사용자에게 상하의의 이름을 입력받아 gui 상에서 두 사진을 보여준뒤, 색 조합표를 보여주고,
하단에 사용자가 고른 옷과 더 괜찮은 조합에 대한 피드백을 출력하는 것이 필요합니다.

**Comment by Bakhyoungwoo** [comment]
상하의 입력받는거는 옷 이름을 전체로 입력받는 것으로 하는게 어떨까요

**Comment by MuHaRVEY** [comment]
옷 이름을 입력받는 것이 정확할 것 같긴합니다.
다만,  옷 이름에 기호 등의 불필요한 내용을 사용자가 입력할 것 같진 않으니 지금까지 해온 것처럼 유사도로 하는 방안도 괜찮을듯 합니다.

**Comment by Bakhyoungwoo** [comment]
색에 관해서는 예를 들어 gray 나 회색의 경우 동일한 의미이지만 이를 검출하는 부분이 필요한 것 같습니다
