### ISSUE TITLE
구현할 색 조합 추천 기능에 대한 질문

### ISSUE THREAD

**Issue by MuHaRVEY** [Bakhyoungwoo/Opensource-destiny-#37]
사용자에게 입력을 받아 상의 하의 정보를 불러올때 분류 기준이 있어야 할 것입니다.

제가 궁금한 것은 저희의 엑셀이 어떤 식으로 통합될 예정인지 입니다.

엑셀 하나에 상의 하의 data가 전부 들어가 새로운 '열'을 만들어 상의, 하의를 행마다 입력하여 구분할 것인지

아니면, 엑셀을 총 2개를 만들어 각각 하나의 엑셀 상의, 하의 옷들을 저장해놓을 것인지 알아야 기능을 구현할 방향을 미리 정할 수 있을 거 같습니다.

**Comment by Bakhyoungwoo** [comment]
최대한 사용자의 편의를 위해 하나로 합치는 게 좋겠지만 그것이 불가능 하다면 상의와 하의로 구분 하는 것이 좋을 듯 합니다.

**Comment by wan-su-2020** [comment]
상의와 하의 각각의 데이터가 엑셀 두 개로 구분되고 코디의 경우 codi열과 situation열을 사용하여 하나의 파일에 전부 모을 예정입니다. 현재 예시의 경우 이슈에 올려놓았습니다.
