### ISSUE TITLE
사용자에게 제공할 수 있는 추가적인 서비스

### ISSUE THREAD

**Issue by wan-su-2020** [Bakhyoungwoo/Opensource-destiny-#4]
상황에 맞는 옷 추천 같은 기능처럼 소비자들이 원하는 기능에 대해 생각해보는거 어떤가요?
ex) 검정색 옷을 원하여 검정색을 검색하면 검정색 관련된 옷이 뜨는 기능

**Comment by Bakhyoungwoo** [comment]
사용자의 체형에 따른 옷을 예측해서 추천해주는 기능이 있다면 좋을듯 합니다.

**Comment by MuHaRVEY** [comment]
앞서 말한 사용자의 체형 통해 옷을 예측해서 추천해주는 기능에서, 사용자의 체형을 예측하는 방식을 키와 몸무게를 통해 BMI를 계산하는 방식으로 하면 어떨까요
