### ISSUE TITLE
색 조합 평가 및 피드백 기능에 대한 토의

### ISSUE THREAD

**Issue by MuHaRVEY** [Bakhyoungwoo/Opensource-destiny-#40]
사용자가 고른 옷에 대한 피드백을 일일히 추가하는 것은 어려울 것이라 생각하여 GPT API를 사용하고자 했으나.

무료 버전의 경우 할당량이 매우 작아 저희의 방향성을 충족하지 못했습니다.

유감스럽게도 일일히 색깔에 대한 평가를 지정해주는 방법외에는 방도가 보이지 않아 단순하게 나아가야할듯합니다.

의견이 있다면 말해주시면 감사하겠습니다.

**Comment by MuHaRVEY** [comment]
![2020-04-28_173B03_(4)](https://github.com/Bakhyoungwoo/Opensource-destiny-/assets/73337570/78d220e0-844c-479f-bba4-983557ebbbb3)

해당 이미지를 기반으로 색조합 기능을 제공하겠습니다.

**Comment by Bakhyoungwoo** [comment]
우선 상의를 기준으로 사람들이 제일 많이 선호하는 순서대로 저희끼리 임의의 등급을 나눠 추천해주는게 어떤가 싶습니다.

**Comment by MuHaRVEY** [comment]
단순 하드코딩으로 딕셔너리를 구성하여서 로직을 추가하는데에 어려움이 있습니다 ㅠㅠ

향후 계속해서 토의해봐야 할 듯 합니다.

**Comment by wan-su-2020** [comment]
그렇다면 위에 올린 사진을 사용하여 상의 혹은 하의와 색깔을 입력시 이에 맞는 색깔을 단어로 출력해서 보여주는 것은 어떠한가요? ex) 상의, 레드 입력시 진청, 블랙이 화면에 출력
