### ISSUE TITLE
gui 에 사용될 모듈 변화

### ISSUE THREAD

**Issue by Bakhyoungwoo** [Bakhyoungwoo/Opensource-destiny-#41]
현재 tkinter 모듈을 이용하여 제작 중인데 기술상의 문제와 코드가 매우 읽기에 부적절하여 보다 간편하고 더 잘 꾸밀 수 있는 pyQt5 모듈을 사용하려고 합니다. 혹시 궁금한 점 있으면 말씀해 주십쇼,

**Comment by MuHaRVEY** [comment]
확실히 인터페이스 방식을 만드는 데에 tkinter 보다 수월할 거 같습니다. 그 외에 작동 방식에서 변화가 생기는 문제점은 없는건가요?

**Comment by Bakhyoungwoo** [comment]
서로 비슷한 방식으로 작동하고 코드를 작성하고 작동시켜본 결과 따로 문제가 없었습니다. 그리고 Pyqt5의 경우 designer 모듈이 있어 거기서 디자인이 가능하여 tkinter 모듈 보다 효율적인 것 같습니다.

**Comment by wan-su-2020** [comment]
그렇다면 gui 예시 사진을 한 번 올려주시는 것도 저희가 비교하고 판단한는데 도움이 될 것 같습니다.

**Comment by Bakhyoungwoo** [comment]
사실 서로 차이점이 없다고 생각합니다. 하지만 PyQt가 화면을 꾸미기에 더 효율적입니다.
