### ISSUE TITLE
파이썬으로 엑셀 파일 병합하였습니다(두 개의 파일을 예시로 합침).  현재 파일 병합 예시를 올렸는데 추가적으로 수정 사항 있으시면 말해주세요

### ISSUE THREAD

**Issue by wan-su-2020** [Bakhyoungwoo/Opensource-destiny-#42]
![image](https://github.com/Bakhyoungwoo/Opensource-destiny-/assets/74997205/5f0e68fb-0d9c-4695-bda5-e22201aa34bc)

**Comment by MuHaRVEY** [comment]
좋습니다.

만일 향후에 엑셀에 따로 열을 추가하는 방식으로 방식을 변경하지 않는 한, 별도의 수정사항은 없을 거 같습니다.

**Comment by Bakhyoungwoo** [comment]
저도 현재로써는 별다른 변동 사항은 없을 거라고 생각됩니다.
