### ISSUE TITLE
price_for_cloth.py 추천 옷 출력 양식에 대한 토의

### ISSUE THREAD

**Issue by MuHaRVEY** [Bakhyoungwoo/Opensource-destiny-#43]
어제 점심 이후에 박형우 학생과 함께 이야기를 나눈 것과 같이

[무료반품] 등의 불필요한 내용은

추천하는 옷의 이름을 출력해줄때 출력되지 않도록 코드를 수정해보겠습니다.

관련되는 내용이 있다면 의견 제시 바랍니다.

**Comment by MuHaRVEY** [comment]
[무료반품] 키워드가 출력되지 않도록 수정했습니다. 참고바랍니다.

**Comment by Bakhyoungwoo** [comment]
그 외에 옷 이름을 제외한 다른 텍스트가 있는지 확인 해 봐야 할 것 같습니다. 필터기능을 하는 함수가 있다면 좋을 것 같습니다.
