### ISSUE TITLE
이미지들을 삽입한 엑셀파일에 옷과 코디를 담은 엑셀파일 처럼 title열이 필요한지 궁금합니다.

### ISSUE THREAD

**Issue by wan-su-2020** [Bakhyoungwoo/Opensource-destiny-#44]

**Comment by MuHaRVEY** [comment]
지금처럼 엑셀의 title열, price열 situation, gender, color 등의 열이 각각 존재했듯이

img 열을 따로 추가하여
각 셀 하나에 이미지가 추가되면 정말 편리하도록 저희가 원하는 기능을 구현할 수 있을 것입니다. ㅠㅠ

**Comment by wan-su-2020** [comment]
img파일을 엑셀 셀에 저장하는 것보다 경로를 통해 이미지를 불러오는 것이 합당하다고 박형우 학생과 토의했습니다. 그러하여 이러한 방식으로 이미지를 불러오도록 하겠습니다.
