### ISSUE TITLE
비슷한 가격대 추천 기능 : price_for_cloth.py 관련 수정사항 있습니다.

### ISSUE THREAD

**Issue by MuHaRVEY** [Bakhyoungwoo/Opensource-destiny-#47]
입력을 할때 저희가 뽑아온 title에는 패키지, 5/15 배송, 무료반품 등 불필요한 키워드가 많이 있어 이에 대한 정확한 입력을 주는 것은 솔직히 좋은 기능이라고 생각되지가 않습니다.

때문에 지금껏 다른 기능에서 그랬듯이 유사도 검사 함수를 정의하여 앞서 말한 불필요한 키워드들을 포함하지 않더라도 검색이 가능하도록 수정하였습니다.

**Comment by wan-su-2020** [comment]
좋습니다!
