### ISSUE TITLE
차이점으로 키와 몸무게를 통해 size를 구현하는 코드를 만드는 것은 어떤가요?

### ISSUE THREAD

**Issue by wan-su-2020** [Bakhyoungwoo/Opensource-destiny-#48]

**Comment by MuHaRVEY** [comment]
차이점으로 내세울 수 있을지는 모르겠지만, 구현가능하다면 저희 프로그램의 완성도가 보다 높아질 수 있을듯 합니다.

저번에 bmi를 내세우는 방법은 구현이 어려워 포기했었는데, 이번엔 가능한 방안이 있나요?

**Comment by wan-su-2020** [comment]
bmi를 사용하는 것은 어려울 것이라고 판단하여 유명 옷 사이트의 리뷰들을 보면 구매자의 키, 몸무게 그리고 구매한 옷의 사이즈에 대한 정보가 있습니다. 이를 기반으로 데이터를 수집하여 사이즈를 예측해주는 프로그램을 구현할 예정입니다.
