### ISSUE TITLE
사이즈 화면 입니다.

### ISSUE THREAD

**Issue by Bakhyoungwoo** [Bakhyoungwoo/Opensource-destiny-#49]
![image](https://github.com/Bakhyoungwoo/Opensource-destiny-/assets/128560371/52ac7391-0bf7-4865-bb5f-3e2bd5eec4b3)
수정사항 있으시면 말씀 해 주시면 감사하겠습니다.

**Comment by wan-su-2020** [comment]
![image](https://github.com/Bakhyoungwoo/Opensource-destiny-/assets/74997205/0fc081b8-73fc-478b-95a7-98016fb36ded)
위의 사진은 무신사의 사이즈 기준표를 캡쳐한 것 입니다. 이런식으로 사이즈 기준표를 넣어주는 것은 어떠할까요

**Comment by Bakhyoungwoo** [comment]
좋은 의견 입니다. 수정해서 반영하도록 하겠습니다.

**Comment by Bakhyoungwoo** [comment]
혹시 여성 의류도 올려주실 수 있나요?

**Comment by Bakhyoungwoo** [comment]
마무리 하겠습니다
