### ISSUE TITLE
명칭(브랜치명)등 정리

### ISSUE THREAD

**Issue by Bakhyoungwoo** [Bakhyoungwoo/Opensource-destiny-#5]
브랜치를 이제 작성해서 해야 할텐데 그 전에 명칭을 저희 끼리 통일해야 서로 혼선이 없을 것 같습니다.

**Comment by Bakhyoungwoo** [comment]
교수님께서 브랜치를 Feature_로 시작 하라고 하셨던 것 같은데 어떻게 통일하는 게 좋을까요?

**Comment by MuHaRVEY** [comment]
'feature_' 은 주어진 필수 사항이라 변경 불가능하고 뒤에 그냥 기능을 붙이면 어떨까요

**Comment by wan-su-2020** [comment]
확실히 그냥 숫자 부여하는 것 보다 어떤 기능을 하는지 붙이는게 이해하기도 좋고 나중에 헷갈리지도 않을 거 같아서 좋아보이네요

**Comment by Bakhyoungwoo** [comment]
그렇다면 Feature_기능이름_이름 으로 정하는 것으로 하겠습니다.
그리고 커밋 이름은 기능_수정1 이런식으로 하는건 어떨까요

**Comment by MuHaRVEY** [comment]
좋습니당
