### ISSUE TITLE
상황별 코디 추천 화면 입니다.

### ISSUE THREAD

**Issue by Bakhyoungwoo** [Bakhyoungwoo/Opensource-destiny-#50]
![image](https://github.com/Bakhyoungwoo/Opensource-destiny-/assets/128560371/50be4c1d-6f08-4d03-8ff3-5bad88ac4fce)
수정사항 있으시면 말씀해 주세요

**Comment by MuHaRVEY** [comment]
고생하셨습니다.
왼쪽의 글씨가 약간만 중앙 쪽으로 이동하면 더 보기 좋을듯 합니다.

**Comment by wan-su-2020** [comment]
gui에 ex)현재 추천된 코디 상황: 가을/ 이런식으로 사용자에게 한 번더 상황을 보여주는 것을 추가하는건 어떤가요

**Comment by Bakhyoungwoo** [comment]
수정해보겠습니다.
