### ISSUE TITLE
현재까지 대략적으로 구현한 size 예측 코드입니다. 두 분의 사이즈 정보도 답글 달아주시면 감사하겠습니다.

### ISSUE THREAD

**Issue by wan-su-2020** [Bakhyoungwoo/Opensource-destiny-#58]
![image](https://github.com/Bakhyoungwoo/Opensource-destiny-/assets/74997205/99a7b030-acb3-4595-a16b-8ca43881048f)
대략적인 코드입니다. 배열안에 데이터들을 이용하여 사이즈를 예측하고 있기에 데이터가 많을 수록 좋습니다. 크롤링을 통해 데이터를 수집하고 있는데 두 분의 데이터도 답글로 알려주시면 감사하겠습니다.

**Comment by Bakhyoungwoo** [comment]
180 80입니다.

**Comment by MuHaRVEY** [comment]
168 64 입니다

**Comment by wan-su-2020** [comment]
옷 사이즈도 알고 계신다면 올려주세요!!

**Comment by MuHaRVEY** [comment]
보통 100 (large)입습니다

**Comment by Bakhyoungwoo** [comment]
XL입니다
