### ISSUE TITLE
개발 시작을 위한 데이터 수집 진행 방향

### ISSUE THREAD

**Issue by MuHaRVEY** [Bakhyoungwoo/Opensource-destiny-#6]
고안한 프로젝트 진행을 위해 데이터 수집을 어떻게 진행하고 기한을 어떻게 할지 1차적으로 논의합시당

**Comment by Bakhyoungwoo** [comment]
우선 저희 주제가 옷 관련 주제 인 만큼 옷에 대한 데이터가 필요할 것 같네요

**Comment by MuHaRVEY** [comment]
그러면 먼저 "1. 옷에 대한 데이터를 수집"하고 주제를 정할때 논의했던 대로,
몇가지 "상황에 적절한 옷을 예측하여 사용자에게 추천해주기 위한 데이터"가 필요할텐데 각각의 데이터 역할 분배를 어떻게 해야할까요

**Comment by wan-su-2020** [comment]
상황에 적절한 옷을 예측하는 데이터 뿐만 아닌 사용자의 신체 조건에 따른 옷의 사이즈 또한 데이터 수집이 필요한 것 같습니다.
