### ISSUE TITLE
저희가 프로그램을 완성본을 영상으로 보여줄지 아니면 직접 시현되는 모습을 보여줄지의 논의가 필요합니다

### ISSUE THREAD

**Issue by wan-su-2020** [Bakhyoungwoo/Opensource-destiny-#69]

**Comment by Bakhyoungwoo** [comment]
일단 ppt를 만들어 보고 시간을 체크한 후에 시간이 많이 부족하다면 영상으로 녹화 후에 발표 자료로 쓰는 게 좋을 것 같네요

**Comment by MuHaRVEY** [comment]
저희 채점 기준 사항에 결과물 항목이 꽤나 큰 부분을 차지합니다.
저희가 만든 결과물의 완성도를 최대한 많이 보여줄 수 있는 방식으로 채택하는 것을 선정해야 할 것 같습니다.
