### ISSUE TITLE
데이터 수집을 위해 크롤링이란 방법을 사용할 때의 주의점

### ISSUE THREAD

**Issue by Bakhyoungwoo** [Bakhyoungwoo/Opensource-destiny-#7]
크롤링을 이용하여 웹 데이터를 수집할 예정인데 이게 불법의 여지가 있어서 한번 논의해 보면 좋을 듯합니다.

**Comment by MuHaRVEY** [comment]
크롤링한 데이터를 기반으로 타인에게 서비스를 제공, 이득을 얻는 행위가 포함되어야 불법이기 때문에 우리는 단순히 과제를 위한 구현이라 불법의 여지는 없을 거 같습니다.

**Comment by wan-su-2020** [comment]
데이터를 크롤링하면서 대상 서버에 무리한 트래픽 요청으로 인한 해당 사이트 이용자들의 정상적인 서비스 이용 방해로 인하여 위볍 판결을 받은 판례가 있습니다. 조심한다면 크롤링 사용에 문제 될 것은 없어 보입니다.

**Comment by Bakhyoungwoo** [comment]
크롤링 자체가 불법은 아니지만 앞서 말한 2가지를 지킨다면 불법은 아닐 것으로 판단됨으로 계속 사용해도 좋을 듯 합니다.
