### ISSUE TITLE
엑셀 파일 통합본 검토 필요

### ISSUE THREAD

**Issue by wan-su-2020** [Bakhyoungwoo/Opensource-destiny-#74]
코디, 상의, 하의 한 번씩 검토할 필요가 있습니다. 현재 열에 잘못된 정보가 입력되있는 부분이 있습니다.

**Comment by MuHaRVEY** [comment]
홈페이지와 저장된 데이터가 같은 title의 다른 사진이라 착오가 좀 있었던 듯 합니다. 죄송합니다 (_ _)

**Comment by wan-su-2020** [comment]
확인했습니다.
