### ISSUE TITLE
현재 크롤링한 데이터를 어떻게 처리해야 할지에 대한 논의 

### ISSUE THREAD

**Issue by MuHaRVEY** [Bakhyoungwoo/Opensource-destiny-#8]
현재 상의, 하의 분류로 옷에 대한 데이터들을 크롤링하여 엑셀 파일로 저장하고 있습니다.

이 데이터를 처리하기 위한 함수를 구현할때 어떤 방식으로 처리를 하여야 할지 논의해봅시다.

**Comment by MuHaRVEY** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/rkddn/AppData/Local/Packages/oice_16_974fa576_32c1d314_ad/AC/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/rkddn/AppData/Local/Packages/oice_16_974fa576_32c1d314_ad/AC/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>



0
--
레이어드 크루 넥 반팔 티셔츠_일반 기장 [화이트]
베이식 긴팔 티셔츠 2팩
[무료반품] 워셔블 하찌 니트 - 11 COLOR
레이어드 크루 넥 반팔 티셔츠_긴 기장 [화이트]
[2PACK] 베이식 무지 레이어드 반팔 티셔츠 일반 기장...
레이어드 크루 넥 반팔 티셔츠_일반 기장 2팩
릴렉스 핏 크루 넥 반팔 티셔츠 [화이트]
[깡스타일리스트 PICK] (시티보이) 오버핏 옥스포드 셔...
에센셜 후드 스웻 셔츠 (MELANGE GREY)
[패키지 상품] Longsleeve 무지 긴팔티
베이식 긴팔 티셔츠 [화이트]
(23SS) 2 TONE ARCH HOODIE GRAY
980g pigment mtm-charcoal-
[무료반품] 코튼 워셔블 하찌 하프집업 니트_5 COLOR...
베이식 크루 넥 반팔 티셔츠 [화이트]
[SS Ver.]헤비 코튼 오버 럭비 맨투맨_Midnigh...
워셔블 하프 집업 카라넥 하찌 니트 (PURE BLACK)...
화란 세미오버 니트 블랙
[무료반품] [리뉴얼] 하프 터틀넥 니트 세트
로그 오버핏 기모 후드 그레이 YHHD2302
[무료반품] [SET] (맨투맨 OR 후드 선택) CGP ...
우먼즈 베이식 크루 넥 반팔 티셔츠 [화이트]
스웨트셔츠 [블랙]
카라 케이블 니트 집업 블랙
[세트]    하프 폴라 니트 티셔츠
LEISURE TIME LOGO SWEATSHIRT NAV...
에센셜 쿨 코튼 2-PACK 티셔츠 블랙
DON’T PANIC PIGMENT SWEATSHIRT P...
[3-PACK]베이직 트래블러 피그먼트 스웨트셔츠
릴렉스 핏 크루 넥 반팔 티셔츠 [블랙]
SIGN LOGO HOOD GRAY
SIGN LOGO HOOD BLACK
릴렉스 핏 크루 넥 반팔 티셔츠 2팩
릴렉스 핏 옥스포드 셔츠 [화이트]
고밀도순면기본반팔티셔츠_3팩 MATS0101
[무료반품] [SET] (맨투맨 OR 후드 선택) CGP ...
[무료반품] 하이 벤트 레이어드 티셔츠 [WHITE]
베이식 크루 넥 반팔 티셔츠 2팩
베이식 긴팔 티셔츠 [블랙]
[무료반품] 오버사이즈 집업 카라 터틀넥 니트 [M.GRE...
오버핏 아치 로고 스웨트 셔츠-그린
쿨 코튼 2-PACK 티셔츠 화이트
[드로우핏X깡스타일리스트] 모크넥 니트 티셔츠 SET
램스울 크루넥 오버니트(연차콜)
(23SS) 2 TONE ARCH TEE WHITE
LAUNDRY SHIRT (LAVENDER GRAY)
SMALL SIGN LOGO SWEATSHIRT BLACK...
021541 레이어드 반팔 티셔츠(2pck)
[무료반품] (솔리드 OR 멀티트위드 선택)_12컬러 코튼...
크래킹 스냅 레글런 후드티 블랙
RALLY COLLARED SWEATSHIRT NAVY(M...
[블랙]SET B-스테디 하프 폴라넥
크루넥 리브 니트 스웨터_블랙
램스울 크루넥 오버니트(블랙)
트위드 크루넥 니트웨어_레몬블랙
컬러 배색 1992 그래픽 후드 (NAVY)
(23SS) (YALE HEAVYWEIGHT) MIXED ...
슬레이크 후드 올리브 HHHD3397
PHYPS® STRAWBERRY HOODIE OATMEAL...
화란 세미오버 니트 크림
[기모] Geppetto 자수 후드 크림
베이식 드레스 셔츠 [화이트]
워셔블 하프 집업 카라넥 하찌 니트 (CURRENT NAV...
[패키지] 더블코튼 무지반팔  패키지 KHST1011
솔리드 옥스포드 오버셔츠(화이트)
오버핏 아치 로고 스웨트 셔츠-네이비
피치스킨 벌룬오버 후드 - 블랙
UNISEX LAUREL OVERSIZED HOODIE -...
[니티드X깡스타일리스트] 코튼 미니멀 라운드 니트 BLAC...
솔리드 케이블 니트 풀오버 투웨이 집업 가디건 카라 자켓
슬레이크 후드 네이비 HHHD3397
폰테 크루 넥 긴팔 티셔츠 [오프 화이트]
[패키지] 에센셜 레이어드 롱 슬리브 티셔츠
에센셜 후드 스웻 셔츠 (BLACK)
(23SS) 2 TONE ARCH HOODIE BLACK
[무료반품] [SET] (긴바지 OR 반바지 선택) 24H...
(23SS) [ONEMILE WEAR] SMALL ARCH...
[UNISEX] 45수 특양면 옆트임 오버핏 반팔티 (화이...
헤비웨이트 오버사이즈 스웨트셔츠 [블랙]
솔리드 옥스포드 오버셔츠(스카이블루)
[무료반품] [패키지] NYC LOCATION T-SHIR...
레이어드 크루 넥 긴팔 티셔츠_일반 기장 [화이트]
[무료반품] 오버사이즈 집업 카라 터틀넥 니트 [BLACK...
미시간 울버린 피그먼트 후드티 블랙 차콜
LAUNDRY SHIRT (LEMON)
오버핏 아치 로고 스웨트 셔츠-와인
TAG HOODIE - ASH
[드로우핏X깡스타일리스트] 터틀넥 니트 티셔츠 SET
[2PACK] 7.5oz 헤비웨이트 무지 오버핏 레이어드 ...
투톤 사선 라운드 니트 - 퍼플



</body>

</html>

**Comment by Bakhyoungwoo** [comment]
데이터를 보관하기에 편리하게 엑셀파일로 저장했음으로 계속 데이터는 이런 방식을 사용하여 저장하면 좋을 듯 하고 처리 방식은 엑셀에서 데이터를 불러와서 배열로 구현하여 처리하는게 어떨까 싶습니다.

**Comment by wan-su-2020** [comment]
하의, 상의 옷에 대한 데이터를 한 엑셀파일을 하나로 통합함과 더불어 가격표 라인을 하나 더 만들어 하의, 상의, 가격이 함께 있는 엑셀파일을 만들어 한번에 처리할 수 있게 하는 것이 좋을 것 같습니다.
