### ISSUE TITLE
기말 발표 준비를 위하여 저희 프로그램의 한계점을 정리해보자 합니다.

### ISSUE THREAD

**Issue by wan-su-2020** [Bakhyoungwoo/Opensource-destiny-#80]
ex) skitlearn 모듈을 사용하여 옷 사이즈를 추천해주는 프로그램을 구현하였지만 키와 몸무게의 데이터를 바탕으로 사이즈를 예측하기 때문에 체형에 따른 세세한 정보가 아니다.

**Comment by Bakhyoungwoo** [comment]
각각의 기능들에 이전으로 돌아가는 버튼이 없는 것이 한계점인 것 같습니다.

**Comment by wan-su-2020** [comment]
색조합표 추천 기능을 단순 하드코딩으로 작업으로 제한척인 추천과 빈약한 평가라는 한계가 있습니다
실시간 데이터가 아니기 때문에 사용자가 검색했을 경우 데이터가 없을 수 있는 등의 한계가 있을 것 같습니다.
