### ISSUE TITLE
사용자의 정보를 활용하여 사용자에게 옷을 추천

### ISSUE THREAD

**Issue by wan-su-2020** [Bakhyoungwoo/Opensource-destiny-#9]
사용자에게 옷을 추천해주기 위해서는 사용자의 정보를 활용하여 옷을 추천해야 하는데 어떤식으로 사용자의 데이터를 수집하고 활용할지 논의합시다.

**Comment by MuHaRVEY** [comment]
일단 사용자가 옷을 입어야 하는 '특정 상황'에 대해서는 직접 단어를 입력받아 유사한 단어를 가진 분류의 코디로 추천해주는 형식으로 만들어볼 수 있습니다.

**Comment by Bakhyoungwoo** [comment]
성별과 색깔도 추가 하는게 좋을 것 같습니다.
